using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using CubeWindow;
using Events;
using QFramework;
using QFramework.Example;
using UnityEngine.UI;

//This script is bound to the confirm button on the main page,the purpose is to create
//a blank mesh based on the coordinates of the four points the user clicked, and open the thumbnail panel.

public class LoadThumbnail : MonoBehaviour
{
    public Material mat;
    public MouseRay mouseRay;
    public Canvas controlCanvas;
   // public int meshCount = 1;
    public CountKeeper countKeeper;
   
    private void Awake()
    {
        mouseRay = Camera.main.GetComponent<MouseRay>();
        controlCanvas = GameObject.Find("ControlCanvas").GetComponent<Canvas>();    
        //Open the Thumbnails panel.
        ResKit.Init();
        UIKit.Root.CanvasScaler.LogInfo();
        countKeeper = FindObjectOfType<CountKeeper>();
    }
    public void OpenThumbnail()//Generate mesh, only for local windows.
    {
        List<Vector3> v = FindObjectOfType<MouseRay>().vertices;
        if (v.Count == 4)
        {
            // Only if 4 point are instantiated can the "Confirm button" be clicked.
            controlCanvas.gameObject.SetActive(false);
            //Reduce the vector square by one thousandth.
            foreach (GameObject ScrObj in mouseRay.screenObjects)
            {
                ScrObj.transform.localScale = new Vector3(1.91f, 1.07f, 0.998f); //  (0.999f, 0.999f, 0.999f)
            }
            Debug.Log(v.Count);
            CreateMesh(v[0],v[1],v[2],v[3],mat);
        }
        else
        {
            Debug.Log(v.Count);
        }
    }

    public void CreateMesh(Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4,Material mat)//The same as the principle of vnc generating mesh, a mesh is generated by two triangles.
    {

        Vector2[] uvs = new Vector2[]
        {
           new Vector2(0, 0),
           new Vector2(1, 0),
           new Vector2(1, 1),
           new Vector2(0, 1),

        };
        
        GameObject newMesh = CreatenewMeshHelper.CreateMeshBy4Point(p1,p2,p3,p4,mat,uvs);        
        newMesh.AddComponent<CreateNewMeshCtrl>();
        newMesh.AddComponent<BoxCollider>();
        newMesh.AddComponent<TextureChange>();
        newMesh.name = "Plane" + countKeeper.count;
        newMesh.tag = "ScreenPlane";
        countKeeper.count++;
        WindowListPop();        
    }
   
    private void WindowListPop()//open thumbnail
    {
        if (UIKit.GetPanel<UIPopWindowsListPanel>())
        {
            UIKit.GetPanel<UIPopWindowsListPanel>().Scale(Vector3.one);//If the thumbnail exists, just change the thumbnail size to 1
        }
        else
        {
            UIKit.OpenPanel<UIPopWindowsListPanel>();//Open the thumbnail if it doesn't exist.
        }
    }   
}


